version: '2'
services:
  orders-service:
    build:
      context: ./../../
    env_file:
      - ./.env
    environment:
      JAVA_OPTIONS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9080 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      branch: ${BRANCH_NAME}
    ports:
      - 8080:8080/tcp
      - 9080:9080/tcp